//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CounterIncreaser
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterInformation
    {
        public int ID { get; set; }
        public int CurrentNumber { get; set; }
        public int NumberAfterAdded { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    }
}
