//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CounterIncreaser
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CounterIncreaserDBEntities : DbContext
    {
        public CounterIncreaserDBEntities()
            : base("name=CounterIncreaserDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CounterInformation> CounterInformations { get; set; }
    
        public virtual int spIncrementLog(Nullable<int> currentNumber, Nullable<int> numberAfterAdded, string status)
        {
            var currentNumberParameter = currentNumber.HasValue ?
                new ObjectParameter("CurrentNumber", currentNumber) :
                new ObjectParameter("CurrentNumber", typeof(int));
    
            var numberAfterAddedParameter = numberAfterAdded.HasValue ?
                new ObjectParameter("NumberAfterAdded", numberAfterAdded) :
                new ObjectParameter("NumberAfterAdded", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spIncrementLog", currentNumberParameter, numberAfterAddedParameter, statusParameter);
        }
    }
}
